# Generated by Django 4.0.3 on 2022-06-09 09:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=users.models.get_avatar_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(None, '(Не указан)'), (0, 'Female'), (1, 'Male')], null=True),
        ),
    ]
