# Generated by Django 4.0.3 on 2022-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='article',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
